CREATE TABLE produtos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR (100),
    preco NUMERIC (10,2),
    PRIMARY KEY (id)
);

create table vendas (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    produto_id INT,
    quantidade NUMERIC (100),
    data_venda DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (id),
    FOREIGN KEY (produto_id) REFERENCES produtos(id)
);


create table log_vendas (
    id SERIAL,
    mensagem TEXT,
    data_log TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);